/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_api_backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest */
        get: operations["get_backtest_api_backtests__backtest_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Backtest
         * @description Delete a run and all its children.
         *
         *     ORM relationships are declared with cascade="all, delete-orphan", so
         *     trades, equity_points, run_metrics, and config_snapshot go with it.
         *     Notes keep a nullable FK and are not cascade-deleted — they survive
         *     as floating research notes.
         */
        delete: operations["delete_backtest_api_backtests__backtest_id__delete"];
        options?: never;
        head?: never;
        /** Update Backtest */
        patch: operations["update_backtest_api_backtests__backtest_id__patch"];
        trace?: never;
    };
    "/api/backtests/{backtest_id}/autopsy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Autopsy */
        get: operations["get_autopsy_api_backtests__backtest_id__autopsy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest Config */
        get: operations["get_backtest_config_api_backtests__backtest_id__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Quality */
        get: operations["get_data_quality_api_backtests__backtest_id__data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtest Equity */
        get: operations["list_backtest_equity_api_backtests__backtest_id__equity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/equity.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Equity Csv */
        get: operations["export_equity_csv_api_backtests__backtest_id__equity_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest Metrics */
        get: operations["get_backtest_metrics_api_backtests__backtest_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/metrics.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Metrics Csv */
        get: operations["export_metrics_csv_api_backtests__backtest_id__metrics_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/prop-firm-sim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Prop Firm */
        post: operations["simulate_prop_firm_api_backtests__backtest_id__prop_firm_sim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Backtest Tags
         * @description Replace the full tag list on a run. Empty list clears all tags.
         */
        put: operations["set_backtest_tags_api_backtests__backtest_id__tags_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtest Trades */
        get: operations["list_backtest_trades_api_backtests__backtest_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/trades.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Trades Csv */
        get: operations["export_trades_csv_api_backtests__backtest_id__trades_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Warehouse
         * @description Walk BS_DATA_ROOT and reconcile the datasets table against disk.
         *
         *     Files modified in the last 60s are skipped (in-progress writes).
         *     Idempotent — running it twice in a row is a no-op the second time.
         */
        post: operations["scan_warehouse_api_datasets_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Experiments
         * @description List experiments, optionally filtered.
         *
         *     `strategy_id` filters across all versions of the strategy by joining
         *     Experiment → StrategyVersion. `decision` is validated against
         *     EXPERIMENT_DECISIONS.
         */
        get: operations["list_experiments_api_experiments_get"];
        put?: never;
        /** Create Experiment */
        post: operations["create_experiment_api_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Decisions
         * @description Decision vocabulary, mirrors STRATEGY_STAGES pattern.
         */
        get: operations["list_decisions_api_experiments_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        /** Delete Experiment */
        delete: operations["delete_experiment_api_experiments__experiment_id__delete"];
        options?: never;
        head?: never;
        /** Update Experiment */
        patch: operations["update_experiment_api_experiments__experiment_id__patch"];
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Backtest */
        post: operations["import_backtest_api_import_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/ingester": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingester Status
         * @description Return the live ingester's most recent heartbeat.
         *
         *     404 if the file doesn't exist (ingester not running or never run).
         *     422 if the file exists but is malformed.
         */
        get: operations["get_ingester_status_api_monitor_ingester_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live Monitor Status */
        get: operations["get_live_monitor_status_api_monitor_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Notes
         * @description List notes with optional filters.
         *
         *     Filters AND together. `tag` matches when the value is in the JSON
         *     tags list. `note_type` is validated against NOTE_TYPES.
         */
        get: operations["list_notes_api_notes_get"];
        put?: never;
        /** Create Note */
        post: operations["create_note_api_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Note Types
         * @description Vocabulary endpoint for note_type. Mirrors STRATEGY_STAGES pattern.
         */
        get: operations["list_note_types_api_notes_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Note */
        delete: operations["delete_note_api_notes__note_id__delete"];
        options?: never;
        head?: never;
        /** Update Note */
        patch: operations["update_note_api_notes__note_id__patch"];
        trace?: never;
    };
    "/api/prompts/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Prompt */
        post: operations["generate_prompt_api_prompts_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Modes
         * @description Vocabulary endpoint for the mode picker. Mirrors STRATEGY_STAGES.
         */
        get: operations["list_modes_api_prompts_modes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prop-firm/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_prop_firm_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_api_strategies_get"];
        put?: never;
        /** Create Strategy */
        post: operations["create_strategy_api_strategies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stages
         * @description Lifecycle vocabulary. Frontend pipeline column order.
         */
        get: operations["list_stages_api_strategies_stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy */
        get: operations["get_strategy_api_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Strategy
         * @description Delete a strategy — only allowed when it has zero versions.
         *
         *     This is the "I created the wrong slug, clean it up" path. It will NOT
         *     cascade to delete imported runs + trades + equity + metrics — if a
         *     strategy has versions, we force the user to either delete each
         *     version + its runs explicitly, or archive the strategy instead
         *     (PATCH status="archived").
         *
         *     Returns 409 if the strategy still has versions attached.
         */
        delete: operations["delete_strategy_api_strategies__strategy_id__delete"];
        options?: never;
        head?: never;
        /** Update Strategy */
        patch: operations["update_strategy_api_strategies__strategy_id__patch"];
        trace?: never;
    };
    "/api/strategies/{strategy_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Strategy Runs
         * @description All backtest runs across every version of this strategy.
         *
         *     Replaces the frontend pattern of fetching /api/backtests and
         *     filtering client-side — that approach is O(all runs in the system)
         *     which grows poorly.
         */
        get: operations["list_strategy_runs_api_strategies__strategy_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Strategy Version */
        post: operations["create_strategy_version_api_strategies__strategy_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategy-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Strategy Version
         * @description Delete a version — only allowed when it has zero attached runs.
         *
         *     Before this change, SQLAlchemy's cascade="all, delete-orphan" on
         *     StrategyVersion.runs would silently nuke every imported run, trade,
         *     equity point, and metric with the version. Now the endpoint refuses
         *     with 409 when runs exist and points the caller at the archive flow.
         */
        delete: operations["delete_strategy_version_api_strategy_versions__version_id__delete"];
        options?: never;
        head?: never;
        /** Update Strategy Version */
        patch: operations["update_strategy_version_api_strategy_versions__version_id__patch"];
        trace?: never;
    };
    "/api/strategy-versions/{version_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Archive Strategy Version
         * @description Mark a version archived. Non-destructive — runs/trades/metrics untouched.
         */
        patch: operations["archive_strategy_version_api_strategy_versions__version_id__archive_patch"];
        trace?: never;
    };
    "/api/strategy-versions/{version_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Unarchive Strategy Version */
        patch: operations["unarchive_strategy_version_api_strategy_versions__version_id__unarchive_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutopsyConditionSlice */
        AutopsyConditionSlice: {
            /** Label */
            label: string;
            /** Net R */
            net_r: number;
            /** Trades */
            trades: number;
            /** Win Rate */
            win_rate: number | null;
        };
        /** AutopsyReportRead */
        AutopsyReportRead: {
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Best Conditions */
            best_conditions: components["schemas"]["AutopsyConditionSlice"][];
            /** Edge Confidence */
            edge_confidence: number;
            /** Go Live Recommendation */
            go_live_recommendation: string;
            /** Overall Verdict */
            overall_verdict: string;
            /** Overfitting Warnings */
            overfitting_warnings: string[];
            /** Risk Notes */
            risk_notes: string[];
            /** Strengths */
            strengths: string[];
            /** Suggested Next Test */
            suggested_next_test: string;
            /** Weaknesses */
            weaknesses: string[];
            /** Worst Conditions */
            worst_conditions: components["schemas"]["AutopsyConditionSlice"][];
        };
        /** BacktestRunRead */
        BacktestRunRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** End Ts */
            end_ts: string | null;
            /** Id */
            id: number;
            /** Import Source */
            import_source: string | null;
            /** Name */
            name: string | null;
            /** Session Label */
            session_label: string | null;
            /** Start Ts */
            start_ts: string | null;
            /** Status */
            status: string;
            /** Strategy Version Id */
            strategy_version_id: number;
            /** Symbol */
            symbol: string;
            /** Tags */
            tags?: string[] | null;
            /** Timeframe */
            timeframe: string | null;
        };
        /**
         * BacktestRunTagsUpdate
         * @description PUT /api/backtests/{id}/tags body. Replaces the full tag list.
         */
        BacktestRunTagsUpdate: {
            /** Tags */
            tags?: string[];
        };
        /**
         * BacktestRunUpdate
         * @description PATCH /api/backtests/{id} body. Send `null` to clear the name.
         */
        BacktestRunUpdate: {
            /** Name */
            name?: string | null;
        };
        /** Body_import_backtest_api_import_backtest_post */
        Body_import_backtest_api_import_backtest_post: {
            /** Config File */
            config_file?: string | null;
            /** Equity File */
            equity_file: string;
            /** Import Source */
            import_source?: string | null;
            /** Metrics File */
            metrics_file?: string | null;
            /** Run Name */
            run_name?: string | null;
            /** Session Label */
            session_label?: string | null;
            /** Strategy Name */
            strategy_name?: string | null;
            /** Strategy Slug */
            strategy_slug?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Timeframe */
            timeframe?: string | null;
            /** Trades File */
            trades_file: string;
            /** Version */
            version?: string | null;
        };
        /** ConfigSnapshotRead */
        ConfigSnapshotRead: {
            /** Backtest Run Id */
            backtest_run_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** DataQualityIssue */
        DataQualityIssue: {
            /** Affected Range */
            affected_range?: string | null;
            /** Category */
            category: string;
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Distort Backtest
             * @default unknown
             */
            distort_backtest: string;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
        };
        /** DataQualityReportRead */
        DataQualityReportRead: {
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Dataset Status */
            dataset_status: string;
            /** Deferred Checks */
            deferred_checks: string[];
            /** First Bar Ts */
            first_bar_ts: string | null;
            /** Issues */
            issues: components["schemas"]["DataQualityIssue"][];
            /** Last Bar Ts */
            last_bar_ts: string | null;
            /** Reliability Score */
            reliability_score: number;
            /** Symbol */
            symbol: string;
            /** Total Bars */
            total_bars: number;
        };
        /** DatasetRead */
        DatasetRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Code */
            dataset_code: string;
            /** End Ts */
            end_ts: string | null;
            /** File Path */
            file_path: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Row Count */
            row_count: number | null;
            /** Schema */
            schema: string;
            /** Sha256 */
            sha256: string | null;
            /** Source */
            source: string;
            /** Start Ts */
            start_ts: string | null;
            /** Symbol */
            symbol: string | null;
        };
        /**
         * DatasetScanResult
         * @description POST /api/datasets/scan response — summary of what changed.
         */
        DatasetScanResult: {
            /**
             * Added
             * @description new rows inserted
             */
            added: number;
            /** Errors */
            errors?: string[];
            /**
             * Removed
             * @description rows for files that no longer exist on disk
             */
            removed: number;
            /**
             * Scanned
             * @description files walked
             */
            scanned: number;
            /**
             * Skipped
             * @description files skipped (e.g. recently-modified, in-progress)
             */
            skipped: number;
            /**
             * Updated
             * @description existing rows whose size/mtime changed
             */
            updated: number;
        };
        /** EquityPointRead */
        EquityPointRead: {
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Drawdown */
            drawdown: number | null;
            /** Equity */
            equity: number;
            /** Id */
            id: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** ExperimentCreate */
        ExperimentCreate: {
            /** Baseline Run Id */
            baseline_run_id?: number | null;
            /** Change Description */
            change_description?: string | null;
            /**
             * Decision
             * @default pending
             */
            decision: string;
            /** Hypothesis */
            hypothesis: string;
            /** Notes */
            notes?: string | null;
            /** Strategy Version Id */
            strategy_version_id: number;
            /** Variant Run Id */
            variant_run_id?: number | null;
        };
        /**
         * ExperimentDecisionsRead
         * @description GET /api/experiments/decisions body.
         */
        ExperimentDecisionsRead: {
            /** Decisions */
            decisions?: string[];
        };
        /** ExperimentRead */
        ExperimentRead: {
            /** Baseline Run Id */
            baseline_run_id: number | null;
            /** Change Description */
            change_description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decision */
            decision: string;
            /** Hypothesis */
            hypothesis: string;
            /** Id */
            id: number;
            /** Notes */
            notes: string | null;
            /** Strategy Version Id */
            strategy_version_id: number;
            /** Updated At */
            updated_at: string | null;
            /** Variant Run Id */
            variant_run_id: number | null;
        };
        /**
         * ExperimentUpdate
         * @description PATCH /api/experiments/{id} body. Only fields present are applied.
         */
        ExperimentUpdate: {
            /** Baseline Run Id */
            baseline_run_id?: number | null;
            /** Change Description */
            change_description?: string | null;
            /** Decision */
            decision?: string | null;
            /** Hypothesis */
            hypothesis?: string | null;
            /** Notes */
            notes?: string | null;
            /** Variant Run Id */
            variant_run_id?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ImportBacktestResponse */
        ImportBacktestResponse: {
            /** Backtest Id */
            backtest_id: number;
            /** Config Imported */
            config_imported: boolean;
            /** Equity Points Imported */
            equity_points_imported: number;
            /** Metrics Imported */
            metrics_imported: boolean;
            /** Strategy Id */
            strategy_id: number;
            /** Strategy Version Id */
            strategy_version_id: number;
            /** Trades Imported */
            trades_imported: number;
        };
        /**
         * IngesterStatus
         * @description Live ingester heartbeat — mirror of {DATA_ROOT}/heartbeat/live_ingester.json.
         *
         *     Written by app.ingest.live every HEARTBEAT_INTERVAL_SEC. Read by
         *     GET /api/monitor/ingester so the UI can show live feed health.
         *
         *     `data_schema` is aliased to "schema" for both input and output so the
         *     on-disk JSON key stays "schema" without shadowing BaseModel.schema().
         */
        IngesterStatus: {
            /** Current Date */
            current_date: string | null;
            /** Current File */
            current_file: string | null;
            /** Dataset */
            dataset: string;
            /** Last Error */
            last_error: string | null;
            /** Last Tick Ts */
            last_tick_ts: string | null;
            /** Reconnect Count */
            reconnect_count: number;
            /** Schema */
            schema: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Stype In */
            stype_in: string;
            /** Symbols */
            symbols: string[];
            /** Ticks Last 60S */
            ticks_last_60s: number;
            /** Ticks Received */
            ticks_received: number;
            /** Uptime Seconds */
            uptime_seconds: number;
        };
        /** LiveMonitorStatus */
        LiveMonitorStatus: {
            /** Current Session */
            current_session: string | null;
            /** Current Symbol */
            current_symbol: string | null;
            /** Last Error */
            last_error: string | null;
            /** Last Heartbeat */
            last_heartbeat: string | null;
            /** Last Signal */
            last_signal: {
                [key: string]: unknown;
            } | string | null;
            /** Raw */
            raw: {
                [key: string]: unknown;
            } | null;
            /** Source Exists */
            source_exists: boolean;
            /** Source Path */
            source_path: string;
            /** Strategy Status */
            strategy_status: string;
            /** Today Pnl */
            today_pnl: number | null;
            /** Today R */
            today_r: number | null;
            /** Trades Today */
            trades_today: number | null;
        };
        /** NoteCreate */
        NoteCreate: {
            /** Backtest Run Id */
            backtest_run_id?: number | null;
            /** Body */
            body: string;
            /**
             * Note Type
             * @default observation
             */
            note_type: string;
            /** Strategy Id */
            strategy_id?: number | null;
            /** Strategy Version Id */
            strategy_version_id?: number | null;
            /** Tags */
            tags?: string[] | null;
            /** Trade Id */
            trade_id?: number | null;
        };
        /** NoteRead */
        NoteRead: {
            /** Backtest Run Id */
            backtest_run_id: number | null;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Note Type */
            note_type: string;
            /** Strategy Id */
            strategy_id: number | null;
            /** Strategy Version Id */
            strategy_version_id: number | null;
            /** Tags */
            tags: string[] | null;
            /** Trade Id */
            trade_id: number | null;
            /** Updated At */
            updated_at: string | null;
        };
        /**
         * NoteTypesRead
         * @description GET /api/notes/types body. Surfaces NOTE_TYPES vocabulary so the
         *     frontend stays driven by the backend.
         */
        NoteTypesRead: {
            /** Types */
            types?: string[];
        };
        /**
         * NoteUpdate
         * @description PATCH /api/notes/{id} body. Only fields present in the request
         *     are applied; omit a field to leave it untouched. Cannot move a note
         *     between attachments — delete and recreate for that.
         */
        NoteUpdate: {
            /** Body */
            body?: string | null;
            /** Note Type */
            note_type?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * PromptGenerateRequest
         * @description POST /api/prompts/generate body.
         */
        PromptGenerateRequest: {
            /** Focus Question */
            focus_question?: string | null;
            /**
             * Mode
             * @default researcher
             */
            mode: string;
            /** Strategy Id */
            strategy_id: number;
        };
        /**
         * PromptGenerateResponse
         * @description POST /api/prompts/generate response.
         *
         *     `prompt_text` is the full markdown blob ready to paste.
         *     `bundled_context_summary` lists which sections were included so the
         *     UI can show the user what got packaged (e.g., "3 versions, 12 notes,
         *     2 experiments, latest run, autopsy"). It's diagnostic, not load-bearing.
         */
        PromptGenerateResponse: {
            /** Bundled Context Summary */
            bundled_context_summary: string[];
            /** Char Count */
            char_count: number;
            /** Mode */
            mode: string;
            /** Prompt Text */
            prompt_text: string;
            /** Strategy Id */
            strategy_id: number;
        };
        /**
         * PromptModesRead
         * @description GET /api/prompts/modes body.
         */
        PromptModesRead: {
            /** Modes */
            modes?: string[];
        };
        /**
         * PropFirmConfigIn
         * @description POST body. Either pass `preset_key` (with optional overrides) or fully
         *     specify every field.
         */
        PropFirmConfigIn: {
            /** Consistency Pct */
            consistency_pct?: number | null;
            /** Daily Loss Limit */
            daily_loss_limit?: number | null;
            /** Max Drawdown */
            max_drawdown: number;
            /** Max Trades Per Day */
            max_trades_per_day?: number | null;
            /** Profit Target */
            profit_target: number;
            /** Risk Per Trade Dollars */
            risk_per_trade_dollars: number;
            /** Starting Balance */
            starting_balance: number;
            /**
             * Trailing Drawdown
             * @default true
             */
            trailing_drawdown: boolean;
        };
        /** PropFirmDayRow */
        PropFirmDayRow: {
            /** Balance At Eod */
            balance_at_eod: number;
            /** Date */
            date: string;
            /** Pnl */
            pnl: number;
            /** Trades */
            trades: number;
        };
        /** PropFirmPresetRead */
        PropFirmPresetRead: {
            /** Consistency Pct */
            consistency_pct: number | null;
            /** Daily Loss Limit */
            daily_loss_limit: number | null;
            /** Key */
            key: string;
            /** Max Drawdown */
            max_drawdown: number;
            /** Max Trades Per Day */
            max_trades_per_day: number | null;
            /** Name */
            name: string;
            /** Notes */
            notes: string;
            /** Profit Target */
            profit_target: number;
            /** Risk Per Trade Dollars */
            risk_per_trade_dollars: number;
            /** Starting Balance */
            starting_balance: number;
            /** Trailing Drawdown */
            trailing_drawdown: boolean;
        };
        /** PropFirmResultRead */
        PropFirmResultRead: {
            best_day: components["schemas"]["PropFirmDayRow"] | null;
            /** Best Day Share Of Profit */
            best_day_share_of_profit: number | null;
            /** Consistency Ok */
            consistency_ok: boolean | null;
            /** Days */
            days: components["schemas"]["PropFirmDayRow"][];
            /** Days Simulated */
            days_simulated: number;
            /** Days To Pass */
            days_to_pass: number | null;
            /** Fail Reason */
            fail_reason: string | null;
            /** Final Balance */
            final_balance: number;
            /** Max Drawdown Reached */
            max_drawdown_reached: number;
            /** Passed */
            passed: boolean;
            /** Peak Balance */
            peak_balance: number;
            /** Skipped Trades No R */
            skipped_trades_no_r: number;
            /** Total Profit */
            total_profit: number;
            /** Total Trades */
            total_trades: number;
            worst_day: components["schemas"]["PropFirmDayRow"] | null;
        };
        /** RunMetricsRead */
        RunMetricsRead: {
            /** Avg Loss */
            avg_loss: number | null;
            /** Avg R */
            avg_r: number | null;
            /** Avg Win */
            avg_win: number | null;
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Best Trade */
            best_trade: number | null;
            /** Id */
            id: number;
            /** Longest Losing Streak */
            longest_losing_streak: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Net Pnl */
            net_pnl: number | null;
            /** Net R */
            net_r: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Trade Count */
            trade_count: number | null;
            /** Win Rate */
            win_rate: number | null;
            /** Worst Trade */
            worst_trade: number | null;
        };
        /**
         * StrategyCreate
         * @description POST /api/strategies body.
         */
        StrategyCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Status
             * @default idea
             */
            status: string;
            /** Tags */
            tags?: string[] | null;
        };
        /** StrategyRead */
        StrategyRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Tags */
            tags: string[] | null;
            /**
             * Versions
             * @default []
             */
            versions: components["schemas"]["StrategyVersionRead"][];
        };
        /**
         * StrategyStagesRead
         * @description GET /api/strategies/stages body. Exposes the lifecycle vocabulary so
         *     the frontend pipeline board column order is driven by the backend.
         */
        StrategyStagesRead: {
            /** Stages */
            stages?: string[];
        };
        /**
         * StrategyUpdate
         * @description PATCH /api/strategies/{id} body. Only fields present in the request
         *     are applied; omit a field to leave it untouched.
         */
        StrategyUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Status */
            status?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * StrategyVersionCreate
         * @description POST /api/strategies/{id}/versions body.
         */
        StrategyVersionCreate: {
            /** Entry Md */
            entry_md?: string | null;
            /** Exit Md */
            exit_md?: string | null;
            /** Git Commit Sha */
            git_commit_sha?: string | null;
            /** Risk Md */
            risk_md?: string | null;
            /** Version */
            version: string;
        };
        /** StrategyVersionRead */
        StrategyVersionRead: {
            /** Archived At */
            archived_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entry Md */
            entry_md: string | null;
            /** Exit Md */
            exit_md: string | null;
            /** Git Commit Sha */
            git_commit_sha: string | null;
            /** Id */
            id: number;
            /** Risk Md */
            risk_md: string | null;
            /** Strategy Id */
            strategy_id: number;
            /** Version */
            version: string;
        };
        /**
         * StrategyVersionUpdate
         * @description PATCH /api/strategy-versions/{id} body.
         */
        StrategyVersionUpdate: {
            /** Entry Md */
            entry_md?: string | null;
            /** Exit Md */
            exit_md?: string | null;
            /** Git Commit Sha */
            git_commit_sha?: string | null;
            /** Risk Md */
            risk_md?: string | null;
            /** Version */
            version?: string | null;
        };
        /** TradeRead */
        TradeRead: {
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Entry Price */
            entry_price: number;
            /**
             * Entry Ts
             * Format: date-time
             */
            entry_ts: string;
            /** Exit Price */
            exit_price: number | null;
            /** Exit Reason */
            exit_reason: string | null;
            /** Exit Ts */
            exit_ts: string | null;
            /** Id */
            id: number;
            /** Pnl */
            pnl: number | null;
            /** R Multiple */
            r_multiple: number | null;
            /** Side */
            side: string;
            /** Size */
            size: number;
            /** Stop Price */
            stop_price: number | null;
            /** Symbol */
            symbol: string;
            /** Tags */
            tags: string[] | null;
            /** Target Price */
            target_price: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_backtests_api_backtests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRead"][];
                };
            };
        };
    };
    get_backtest_api_backtests__backtest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_backtest_api_backtests__backtest_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_backtest_api_backtests__backtest_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRunUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_autopsy_api_backtests__backtest_id__autopsy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutopsyReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_config_api_backtests__backtest_id__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSnapshotRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_quality_api_backtests__backtest_id__data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_equity_api_backtests__backtest_id__equity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquityPointRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_equity_csv_api_backtests__backtest_id__equity_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_metrics_api_backtests__backtest_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunMetricsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_metrics_csv_api_backtests__backtest_id__metrics_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_prop_firm_api_backtests__backtest_id__prop_firm_sim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropFirmConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropFirmResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_backtest_tags_api_backtests__backtest_id__tags_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRunTagsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_trades_api_backtests__backtest_id__trades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_trades_csv_api_backtests__backtest_id__trades_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_datasets_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                schema?: string | null;
                source?: string | null;
                kind?: string | null;
                dataset_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_warehouse_api_datasets_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetScanResult"];
                };
            };
        };
    };
    list_experiments_api_experiments_get: {
        parameters: {
            query?: {
                strategy_version_id?: number | null;
                strategy_id?: number | null;
                decision?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_experiment_api_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_api_experiments_decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentDecisionsRead"];
                };
            };
        };
    };
    get_experiment_api_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_experiment_api_experiments__experiment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_experiment_api_experiments__experiment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    import_backtest_api_import_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_backtest_api_import_backtest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingester_status_api_monitor_ingester_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngesterStatus"];
                };
            };
        };
    };
    get_live_monitor_status_api_monitor_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveMonitorStatus"];
                };
            };
        };
    };
    list_notes_api_notes_get: {
        parameters: {
            query?: {
                strategy_id?: number | null;
                strategy_version_id?: number | null;
                backtest_run_id?: number | null;
                trade_id?: number | null;
                note_type?: string | null;
                tag?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_note_types_api_notes_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteTypesRead"];
                };
            };
        };
    };
    delete_note_api_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_prompt_api_prompts_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_modes_api_prompts_modes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptModesRead"];
                };
            };
        };
    };
    list_presets_api_prop_firm_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropFirmPresetRead"][];
                };
            };
        };
    };
    list_strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRead"][];
                };
            };
        };
    };
    create_strategy_api_strategies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stages_api_strategies_stages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyStagesRead"];
                };
            };
        };
    };
    get_strategy_api_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_strategy_api_strategies__strategy_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_strategy_api_strategies__strategy_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategy_runs_api_strategies__strategy_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_strategy_version_api_strategies__strategy_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_strategy_version_api_strategy_versions__version_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_strategy_version_api_strategy_versions__version_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategyVersionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_strategy_version_api_strategy_versions__version_id__archive_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_strategy_version_api_strategy_versions__version_id__unarchive_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
