/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_api_backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest */
        get: operations["get_backtest_api_backtests__backtest_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Backtest
         * @description Delete a run and all its children.
         *
         *     ORM relationships are declared with cascade="all, delete-orphan", so
         *     trades, equity_points, run_metrics, and config_snapshot go with it.
         *     Notes keep a nullable FK and are not cascade-deleted — they survive
         *     as floating research notes.
         */
        delete: operations["delete_backtest_api_backtests__backtest_id__delete"];
        options?: never;
        head?: never;
        /** Update Backtest */
        patch: operations["update_backtest_api_backtests__backtest_id__patch"];
        trace?: never;
    };
    "/api/backtests/{backtest_id}/data-quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Data Quality */
        get: operations["get_data_quality_api_backtests__backtest_id__data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/equity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtest Equity */
        get: operations["list_backtest_equity_api_backtests__backtest_id__equity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest Metrics */
        get: operations["get_backtest_metrics_api_backtests__backtest_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{backtest_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtest Trades */
        get: operations["list_backtest_trades_api_backtests__backtest_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Backtest */
        post: operations["import_backtest_api_import_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live Monitor Status */
        get: operations["get_live_monitor_status_api_monitor_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_api_notes_get"];
        put?: never;
        /** Create Note */
        post: operations["create_note_api_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy */
        get: operations["get_strategy_api_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestRunRead */
        BacktestRunRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** End Ts */
            end_ts: string | null;
            /** Id */
            id: number;
            /** Import Source */
            import_source: string | null;
            /** Name */
            name: string | null;
            /** Session Label */
            session_label: string | null;
            /** Start Ts */
            start_ts: string | null;
            /** Status */
            status: string;
            /** Strategy Version Id */
            strategy_version_id: number;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string | null;
        };
        /**
         * BacktestRunUpdate
         * @description PATCH /api/backtests/{id} body. Send `null` to clear the name.
         */
        BacktestRunUpdate: {
            /** Name */
            name?: string | null;
        };
        /** Body_import_backtest_api_import_backtest_post */
        Body_import_backtest_api_import_backtest_post: {
            /** Config File */
            config_file?: string | null;
            /** Equity File */
            equity_file: string;
            /** Import Source */
            import_source?: string | null;
            /** Metrics File */
            metrics_file?: string | null;
            /** Run Name */
            run_name?: string | null;
            /** Session Label */
            session_label?: string | null;
            /** Strategy Name */
            strategy_name?: string | null;
            /** Strategy Slug */
            strategy_slug?: string | null;
            /** Symbol */
            symbol?: string | null;
            /** Timeframe */
            timeframe?: string | null;
            /** Trades File */
            trades_file: string;
            /** Version */
            version?: string | null;
        };
        /** DataQualityIssue */
        DataQualityIssue: {
            /** Affected Range */
            affected_range?: string | null;
            /** Category */
            category: string;
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Distort Backtest
             * @default unknown
             */
            distort_backtest: string;
            /** Message */
            message: string;
            /** Severity */
            severity: string;
        };
        /** DataQualityReportRead */
        DataQualityReportRead: {
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Dataset Status */
            dataset_status: string;
            /** Deferred Checks */
            deferred_checks: string[];
            /** First Bar Ts */
            first_bar_ts: string | null;
            /** Issues */
            issues: components["schemas"]["DataQualityIssue"][];
            /** Last Bar Ts */
            last_bar_ts: string | null;
            /** Reliability Score */
            reliability_score: number;
            /** Symbol */
            symbol: string;
            /** Total Bars */
            total_bars: number;
        };
        /** EquityPointRead */
        EquityPointRead: {
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Drawdown */
            drawdown: number | null;
            /** Equity */
            equity: number;
            /** Id */
            id: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ImportBacktestResponse */
        ImportBacktestResponse: {
            /** Backtest Id */
            backtest_id: number;
            /** Config Imported */
            config_imported: boolean;
            /** Equity Points Imported */
            equity_points_imported: number;
            /** Metrics Imported */
            metrics_imported: boolean;
            /** Strategy Id */
            strategy_id: number;
            /** Strategy Version Id */
            strategy_version_id: number;
            /** Trades Imported */
            trades_imported: number;
        };
        /** LiveMonitorStatus */
        LiveMonitorStatus: {
            /** Current Session */
            current_session: string | null;
            /** Current Symbol */
            current_symbol: string | null;
            /** Last Error */
            last_error: string | null;
            /** Last Heartbeat */
            last_heartbeat: string | null;
            /** Last Signal */
            last_signal: {
                [key: string]: unknown;
            } | string | null;
            /** Raw */
            raw: {
                [key: string]: unknown;
            } | null;
            /** Source Exists */
            source_exists: boolean;
            /** Source Path */
            source_path: string;
            /** Strategy Status */
            strategy_status: string;
            /** Today Pnl */
            today_pnl: number | null;
            /** Today R */
            today_r: number | null;
            /** Trades Today */
            trades_today: number | null;
        };
        /** NoteCreate */
        NoteCreate: {
            /** Backtest Run Id */
            backtest_run_id?: number | null;
            /** Body */
            body: string;
            /** Trade Id */
            trade_id?: number | null;
        };
        /** NoteRead */
        NoteRead: {
            /** Backtest Run Id */
            backtest_run_id: number | null;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Trade Id */
            trade_id: number | null;
        };
        /** RunMetricsRead */
        RunMetricsRead: {
            /** Avg Loss */
            avg_loss: number | null;
            /** Avg R */
            avg_r: number | null;
            /** Avg Win */
            avg_win: number | null;
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Best Trade */
            best_trade: number | null;
            /** Id */
            id: number;
            /** Longest Losing Streak */
            longest_losing_streak: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Net Pnl */
            net_pnl: number | null;
            /** Net R */
            net_r: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Trade Count */
            trade_count: number | null;
            /** Win Rate */
            win_rate: number | null;
            /** Worst Trade */
            worst_trade: number | null;
        };
        /** StrategyRead */
        StrategyRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Tags */
            tags: string[] | null;
            /**
             * Versions
             * @default []
             */
            versions: components["schemas"]["StrategyVersionRead"][];
        };
        /** StrategyVersionRead */
        StrategyVersionRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entry Md */
            entry_md: string | null;
            /** Exit Md */
            exit_md: string | null;
            /** Git Commit Sha */
            git_commit_sha: string | null;
            /** Id */
            id: number;
            /** Risk Md */
            risk_md: string | null;
            /** Strategy Id */
            strategy_id: number;
            /** Version */
            version: string;
        };
        /** TradeRead */
        TradeRead: {
            /** Backtest Run Id */
            backtest_run_id: number;
            /** Entry Price */
            entry_price: number;
            /**
             * Entry Ts
             * Format: date-time
             */
            entry_ts: string;
            /** Exit Price */
            exit_price: number | null;
            /** Exit Reason */
            exit_reason: string | null;
            /** Exit Ts */
            exit_ts: string | null;
            /** Id */
            id: number;
            /** Pnl */
            pnl: number | null;
            /** R Multiple */
            r_multiple: number | null;
            /** Side */
            side: string;
            /** Size */
            size: number;
            /** Stop Price */
            stop_price: number | null;
            /** Symbol */
            symbol: string;
            /** Tags */
            tags: string[] | null;
            /** Target Price */
            target_price: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_backtests_api_backtests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRead"][];
                };
            };
        };
    };
    get_backtest_api_backtests__backtest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_backtest_api_backtests__backtest_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_backtest_api_backtests__backtest_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRunUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_quality_api_backtests__backtest_id__data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQualityReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_equity_api_backtests__backtest_id__equity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquityPointRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_metrics_api_backtests__backtest_id__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunMetricsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtest_trades_api_backtests__backtest_id__trades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    import_backtest_api_import_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_backtest_api_import_backtest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_monitor_status_api_monitor_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveMonitorStatus"];
                };
            };
        };
    };
    list_notes_api_notes_get: {
        parameters: {
            query?: {
                backtest_run_id?: number | null;
                trade_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRead"][];
                };
            };
        };
    };
    get_strategy_api_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
